theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  parse_block_html: true
title: "HELLO"
description: "Hello."
google_analytics: G-VSNWH55C79

