[build]
publish = "public"
command = "hugo --gc --minify" # --baseURL 'https://aftab700.netlify.app/'"

[build.environment]
HUGO_VERSION = "0.147.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify"

# [[redirects]]
# from = "/*"
# to = "https://aftabsama.com/"
# status = 301
# force = true
# headers = { X-From = "Netlify" }
