name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://aftab700.github.io/
        additional-extensions: doc docx ppt pptx xls xlsx pdf php png jpg jpeg bak sh bash py c cpp htm html 

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6.0.0
      with:
        title: "Automated sitemap update"
        body: > 
          Automated changes. Sitemap updated by 
          the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  
        commit-message: "Automated sitemap update."
        author: Aftab Sama
        committer: Aftab Sama
        #branch: create-pull-request/sitemap
        #delete-branch: true
